### ISSUE TITLE
php script doesn't runs

### ISSUE THREAD

**Issue by aatishballa** [aatishballa/BUAD-3283-ecom-web-dev#2]
Hi, Professor Nate. @natenolting I have a simple php script written for my form. But, it doesn't seem to run. Is it because I need to have php installed on my machine/server that I am using,  in order to run php scripts?

**Comment by aatishballa** [comment]
@natenolting

**Comment by natenolting** [comment]
@aatishballa the easiest thing for you would be to run them on your hosting account. I saw you are not using x10, does the hosting you are using have PHP installed? How are your files structured on your hosting? Can you send me a link to what you're working on?

**Comment by aatishballa** [comment]
Hi, Professor Nate @natenolting. I could get the PHP script running in my localhost (after installing WAMP of my personal computer).  

But, it not running on my hosting account. Seems like PHP is not installed there.

**Comment by aatishballa** [comment]
Hi ! Professor Nate @natenolting, I got it working. Found out that, I was using POST method in my index.html. And, I had GET as my method in backend_contact_form.php file. So, I changed it to POST and now it's working.

**Comment by natenolting** [comment]
Good to hear! Go ahead and close this issue.
